-- The initial schema: websites, schedules, runs.
--
-- Generated by `prisma migrate dev --create-only` from db/schema.prisma, then read and
-- hand-augmented. Exactly two things below are NOT Prisma's output, and both are marked
-- `HAND-WRITTEN` where they appear:
--
--   1. The whole of "runs_status_active_idx". Prisma has no syntax for a partial index,
--      and its introspection cannot see one either — which is why the index is declared
--      HERE ONLY and deliberately not in schema.prisma. Declaring it in both places was
--      tried and is wrong: Prisma would read the database as not having the index and
--      emit a duplicate `CREATE INDEX` on every subsequent `migrate dev`. See the long
--      comment on `model Run` in db/schema.prisma.
--   2. `COMMENT ON COLUMN "schedules"."auto_publish"`, so that the column's reserved
--      status is visible in `\d+` and not only in schema.prisma.
--
-- There is deliberately NO foreign key from "websites"."user_id" to `auth.users`("id").
-- `auth` is Supabase's schema, and this same migration has to apply unchanged to CI's
-- test database, which is a bare `postgres:16` container with no `auth` schema at all
-- (.github/workflows/ci-backend.yml). Supabase Auth is the system of record for users;
-- see the note on `Website.userId` in db/schema.prisma and ARCHITECTURE.md §6.4.

-- CreateEnum
CREATE TYPE "run_trigger" AS ENUM ('manual', 'scheduled');

-- CreateEnum
CREATE TYPE "run_status" AS ENUM ('pending', 'processing', 'completed', 'failed');

-- CreateTable
CREATE TABLE "websites" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "user_id" UUID NOT NULL,
    "url" TEXT NOT NULL,
    "origin" TEXT NOT NULL,
    "title" TEXT,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "websites_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "schedules" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "website_id" UUID NOT NULL,
    "active" BOOLEAN NOT NULL DEFAULT false,
    "interval_minutes" INTEGER NOT NULL,
    "next_run_at" TIMESTAMPTZ(6),
    "last_run_at" TIMESTAMPTZ(6),
    "auto_publish" BOOLEAN NOT NULL DEFAULT false,

    CONSTRAINT "schedules_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "runs" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "website_id" UUID NOT NULL,
    "schedule_id" UUID,
    "trigger" "run_trigger" NOT NULL,
    "status" "run_status" NOT NULL DEFAULT 'pending',
    "started_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "completed_at" TIMESTAMPTZ(6),
    "llms_txt" TEXT,
    "stats" JSONB,
    "error" TEXT,
    "storage_path" TEXT,

    CONSTRAINT "runs_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "websites_user_id_idx" ON "websites"("user_id");

-- CreateIndex
CREATE UNIQUE INDEX "websites_user_id_origin_key" ON "websites"("user_id", "origin");

-- CreateIndex
CREATE UNIQUE INDEX "schedules_website_id_key" ON "schedules"("website_id");

-- CreateIndex
CREATE INDEX "schedules_active_next_run_at_idx" ON "schedules"("active", "next_run_at");

-- CreateIndex
CREATE INDEX "runs_website_id_started_at_idx" ON "runs"("website_id", "started_at" DESC);

-- HAND-WRITTEN (not a Prisma `-- CreateIndex` block — Prisma cannot express this):
-- both scanners of this index — the duplicate-run guard on a manual trigger and the
-- stuck-run reaper — look for exactly these two statuses, and neither cares about
-- completed or failed runs, which are the rows that accumulate forever. Keeping the
-- index partial keeps it proportional to the number of runs in flight rather than to
-- the size of the table.
CREATE INDEX "runs_status_active_idx" ON "runs"("status") WHERE "status" IN ('pending', 'processing');

-- AddForeignKey
ALTER TABLE "schedules" ADD CONSTRAINT "schedules_website_id_fkey" FOREIGN KEY ("website_id") REFERENCES "websites"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "runs" ADD CONSTRAINT "runs_website_id_fkey" FOREIGN KEY ("website_id") REFERENCES "websites"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "runs" ADD CONSTRAINT "runs_schedule_id_fkey" FOREIGN KEY ("schedule_id") REFERENCES "schedules"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- HAND-WRITTEN: Prisma does not emit COMMENT ON. This puts the column's reserved status
-- where someone running `\d+ schedules` will see it, not only in schema.prisma.
COMMENT ON COLUMN "schedules"."auto_publish" IS 'RESERVED, UNUSED: no code reads or writes this column in this milestone. Do not build against it.';
