#!/usr/bin/env bash
# scripts/local-env.sh — bridge `supabase status` into the environment variables the
# backend (backend/app/core/settings.py) and Prisma (db/schema.prisma) expect, without
# ever writing a local Supabase key into a tracked file.
#
# `supabase status -o env` is the only source of truth this script reads from. It prints
# ANON_KEY, API_URL, DB_URL, SECRET_KEY (falling back to SERVICE_ROLE_KEY on older CLI
# versions that don't emit SECRET_KEY), and friends, as shell-quoted `KEY="value"` lines
# on stdout.
#
# Usage:
#   scripts/local-env.sh export
#       Print `export NAME=value` lines for the current shell to `eval`. Intended use:
#           eval "$(scripts/local-env.sh export)"
#
#   scripts/local-env.sh write-db-env
#       Write db/.env (gitignored — see .gitignore) with DIRECT_DATABASE_URL, so the
#       Prisma CLI in db/ can find a local database without any manual edit.
#
# This script must NEVER echo a parsed value to stdout as a human-readable log line — the
# `export` lines are meant to be consumed by `eval`, not read by a person, and every
# status or error message below names variables only, never values (ARCHITECTURE.md §9.4).

set -eu

script_dir="$(cd "$(dirname "$0")" && pwd)"
repo_root="$(cd "$script_dir/.." && pwd)"

usage() {
  echo "Usage: $(basename "$0") {export|write-db-env}" >&2
  exit 2
}

# Reads one KEY="value" line out of `$status_env` and prints the bare value (no quotes).
# Prints nothing if the key is absent.
read_key() {
  key="$1"
  printf '%s\n' "$status_env" | grep "^${key}=" | head -n1 | sed -E "s/^${key}=\"(.*)\"\$/\1/"
}

cmd="${1:-}"
case "$cmd" in
  export | write-db-env) ;;
  *) usage ;;
esac

# One call, one clear failure mode: if the local Supabase stack isn't running, `supabase
# status` exits non-zero and this script stops here with an actionable message rather than
# leaking a half-parsed, empty configuration downstream.
if ! status_env="$(supabase status -o env 2>/dev/null)"; then
  echo "local-env: the local Supabase stack is not running." >&2
  echo "local-env: start it first with \`supabase start\` (or \`make dev\`)." >&2
  exit 1
fi

case "$cmd" in
  export)
    api_url="$(read_key API_URL)"
    db_url="$(read_key DB_URL)"
    secret_key="$(read_key SECRET_KEY)"
    if [ -z "$secret_key" ]; then
      # Older Supabase CLI releases call this key SERVICE_ROLE_KEY.
      secret_key="$(read_key SERVICE_ROLE_KEY)"
    fi

    missing=""
    [ -z "$api_url" ] && missing="$missing API_URL"
    [ -z "$db_url" ] && missing="$missing DB_URL"
    [ -z "$secret_key" ] && missing="$missing SECRET_KEY/SERVICE_ROLE_KEY"
    if [ -n "$missing" ]; then
      echo "local-env: \`supabase status -o env\` did not report:$missing" >&2
      exit 1
    fi

    echo "export SUPABASE_URL=$api_url"
    echo "export SUPABASE_SECRET_KEY=$secret_key"
    echo "export DATABASE_URL=$db_url"
    echo "export DIRECT_DATABASE_URL=$db_url"
    echo "export REDIS_URL=redis://localhost:6379/0"
    ;;

  write-db-env)
    db_url="$(read_key DB_URL)"
    if [ -z "$db_url" ]; then
      echo "local-env: \`supabase status -o env\` did not report DB_URL" >&2
      exit 1
    fi

    db_env_file="$repo_root/db/.env"
    {
      echo "# Generated by scripts/local-env.sh write-db-env. Do not commit — see .gitignore."
      echo "DIRECT_DATABASE_URL=$db_url"
    } >"$db_env_file"
    echo "local-env: wrote DIRECT_DATABASE_URL to db/.env" >&2
    ;;
esac
