/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness-and-readiness probe, polled by Fly every 10 seconds.
         *
         *     **The HTTP status is always 200 as long as this process is alive — dependency health is
         *     reported in the body, never the status code.** This is deliberate: restarting a healthy
         *     web machine does nothing to fix a Postgres or an Upstash outage, it just adds a flapping
         *     fleet of machines on top of one. A non-200 here would make Fly do exactly that. The
         *     `[[http_service.checks]]` block in backend/fly.toml is scoped to the `app` process for
         *     a related reason — the worker serves no HTTP, so a check against it could only ever
         *     fail.
         *
         *     Both checks always run, so `db` and `redis` are always present: `"ok"` when the probe
         *     succeeds, `"timeout"` if it exceeds its budget, `"error"` for anything else. They run
         *     **concurrently**, so one slow dependency does not spend the other's budget and the
         *     endpoint stays inside `_CHECK_TIMEOUT_SECONDS` overall.
         *
         *     `status` is `"ok"` only when both are `"ok"`; otherwise it's `"degraded"`, so a caller
         *     that reads only `status` still gets an accurate signal without having to know the
         *     component values. A degraded queue is a real degradation — the API can still serve every
         *     read, but it cannot start a crawl — and saying so here is free, precisely because
         *     nothing restarts a machine over this body. What "non-fatal" buys is the 200, not a
         *     flattering summary.
         *
         *     **Redis is probed on every call, which is not free.** Fly polls this every 10s, so the
         *     check alone costs 6 × 60 × 24 = 8,640 Redis commands a day. That is real, but it is not
         *     where the money is — an idle worker at `poll_delay = 5` spends twice that (see
         *     `app.worker.settings` for the arithmetic). If it ever needs to come down, cache the
         *     probe result for a few seconds here rather than slowing the Fly check, which is also
         *     the failure detector.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Run
         * @description Return one run in full, including `llms_txt` and `storage_path`.
         *
         *     Any signed-in user may read any run (ARCHITECTURE.md §4.1); `user_id` is present only
         *     to require a token and is deliberately never passed to the service. `404` if `id` names
         *     no run.
         */
        get: operations["get_run_runs__id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/websites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Websites
         * @description List **every** website, from every user, most recently active first.
         *
         *     Not filtered by the caller, on purpose: this application is not multi-tenant and
         *     browsing everyone's sites is the product (ARCHITECTURE.md §4.1). `user_id` is present to
         *     require authentication and is intentionally not passed to the service.
         */
        get: operations["list_websites_websites_get"];
        put?: never;
        /**
         * Create Website
         * @description Register a website, owned by the caller.
         *
         *     The URL is validated by `CreateWebsiteRequest` before this runs, so a malformed one is a
         *     `422` that never reaches the service.
         */
        post: operations["create_website_websites_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/websites/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Website
         * @description Return one website. Any signed-in user may read any website; `404` if unknown.
         *
         *     The path parameter is `id`, not `website_id`, because the noun is already in the path
         *     (ARCHITECTURE.md §10.3). It shadows the `id` builtin inside this function body, which is
         *     the accepted cost of the route contract — nothing here calls `id()`.
         */
        get: operations["get_website_websites__id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Website
         * @description Delete a website the caller owns, along with its schedule and runs.
         *
         *     `403`, not `404`, when the caller is not the owner: `GET /websites/{id}` already returns
         *     this row to every signed-in user, so hiding its existence here would be inconsistent
         *     with the endpoint next to it (ARCHITECTURE.md §4, `app.core.auth.ownership`).
         *
         *     Returns `204` with no body — hence no `response_model` and a `None` return.
         */
        delete: operations["delete_website_websites__id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/websites/{id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Runs
         * @description List one website's run history, newest first. Any signed-in user, any website.
         *
         *     Not filtered by the caller, on purpose (ARCHITECTURE.md §4.1) — `user_id` is present to
         *     require authentication and is intentionally not passed to the service. `404` if `id`
         *     names no website; see `RunService.list_runs`.
         *
         *     The path parameter is `id`, not `website_id`, because the noun is already in the path
         *     (ARCHITECTURE.md §10.3) — it shadows the `id` builtin inside this function body, which
         *     is the accepted cost of the route contract, matching `websites.get_website`.
         */
        get: operations["list_runs_websites__id__runs_get"];
        put?: never;
        /**
         * Trigger Run
         * @description Start a manual crawl of one website. Owner-only — unlike this module's two reads.
         *
         *     `202 Accepted`, not `201 Created`: the body describes a `pending` run that has been
         *     queued, not one that has finished (see `TriggerRunResponse`). Unlike `list_runs` and
         *     `get_run`, `user_id` IS passed to the service here, because this is the one write in
         *     this router and writes are ownership-checked (ARCHITECTURE.md §4.2).
         *
         *     Four things can stop this short of a `202`: `404` if `id` names no website; `403` if the
         *     caller does not own it; `409` if that website already has a run in flight; `429` if the
         *     caller is over their concurrent- or daily-run cap. A `503` is also possible, if the run
         *     was created but could not be queued — see `RunService.trigger_run` for exactly which
         *     check produces which, and `require_queue_pool` above for the one `503` this router
         *     itself can raise before the service even runs.
         */
        post: operations["trigger_run_websites__id__runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/websites/{id}/schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Schedule
         * @description Return one website's schedule. Any signed-in user may read any website's schedule.
         *
         *     `200` with a `null` body when the website exists but has no schedule yet — that is a
         *     normal state, not an error. `404` is reserved for an unknown *website*; a missing
         *     schedule never produces one.
         *
         *     The path parameter is `id`, not `website_id`, because the noun is already in the path
         *     (ARCHITECTURE.md §10.3), matching `get_website` in `api/routers/websites.py`.
         */
        get: operations["get_schedule_websites__id__schedule_get"];
        /**
         * Upsert Schedule
         * @description Create or replace the schedule for a website the caller owns.
         *
         *     Always `200`, never a conditional `201` for the create case. Distinguishing "this was a
         *     create" from "this was an update" would require a branch in this handler — checking
         *     whether a schedule already existed — and CLAUDE.md #6 forbids exactly that: a router
         *     parses input, calls one service method, and returns. The ticket's own wording ("200/201")
         *     permits either; `200` is the one that keeps this file free of logic.
         *
         *     `403`, not `404`, when the caller is not the website's owner — `GET /websites/{id}`
         *     already returns that website to every signed-in user, so hiding its existence here would
         *     be inconsistent with the endpoint next to it (ARCHITECTURE.md §4).
         */
        put: operations["upsert_schedule_websites__id__schedule_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/websites/{id}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Website Stats
         * @description Return one website's run statistics over `window`, bucketed and zero-filled, plus a
         *     whole-window summary. Any signed-in user, any website.
         *
         *     Not filtered by the caller, on purpose (ARCHITECTURE.md §4.1) — `user_id` is present to
         *     require authentication and is intentionally not passed to the service. `404` if `id`
         *     names no website; an unrecognized `window` is a native `422` (`StatsWindowName` is a
         *     `Literal`, so FastAPI rejects it before this handler runs).
         *
         *     The path parameter is `id`, not `website_id`, matching `list_runs` above
         *     (ARCHITECTURE.md §10.3).
         */
        get: operations["get_website_stats_websites__id__stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * CreateWebsiteRequest
         * @description Body of `POST /websites`.
         */
        CreateWebsiteRequest: {
            /**
             * Url
             * @description An absolute http:// or https:// URL. Stored as submitted; its normalized origin (lowercased scheme and host, default port and path removed) is what deduplicates it against your existing websites.
             * @example https://example.com/docs
             */
            url: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Response body for `GET /health`.
         *
         *     This DTO lives beside its route rather than in `app/features/` because health is an
         *     operational endpoint, not a product feature with a service, a reader, and a writer.
         *     It does touch Postgres and Redis — a bounded `SELECT 1` and a bounded `PING`, see
         *     `_probe` — but those are liveness probes rather than data access, which is why there is
         *     no repository behind them.
         *
         *     `db` and `redis` are required, never absent, because the checks that produce them
         *     always run — there is no code path that returns this response without having attempted
         *     both. `redis` reports `"error"` when the API booted without a queue connection at all,
         *     which is a startup outcome the lifespan deliberately allows (see `app.main.lifespan`).
         *
         *     **Field order is part of the contract**, because Pydantic serializes in declaration
         *     order and two places compare this body as an exact string: the `build-check` job in
         *     ci-backend.yml, and the one assertion in tests/test_health.py written against the raw
         *     response text for precisely this reason. The rest of that suite compares parsed dicts,
         *     which is order-independent, and the `smoke` job in deploy-backend.yml reads `db` and
         *     `redis` individually with `jq`, which is too — so neither of those would notice a
         *     reorder, and it is worth knowing which layer is actually holding this invariant.
         */
        HealthResponse: {
            /**
             * Db
             * @enum {string}
             */
            db: "ok" | "error" | "timeout";
            /**
             * Redis
             * @enum {string}
             */
            redis: "ok" | "error" | "timeout";
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
        };
        /**
         * LatestRunSummary
         * @description The compact view of a website's most recent run, folded into the list response.
         *
         *     A fragment of `WebsiteListItemResponse`, never an endpoint's response on its own — the
         *     runs feature owns the full run representation. Only the fields the websites table in the
         *     UI actually renders are here; anything more would make this a second, competing run DTO.
         */
        LatestRunSummary: {
            /** Completed At */
            completed_at: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Pages Crawled */
            pages_crawled: number | null;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "processing" | "completed" | "failed";
        };
        /** Page[RunListItemResponse] */
        Page_RunListItemResponse_: {
            /** Items */
            items: components["schemas"]["RunListItemResponse"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /**
         * RunAlreadyInFlightDetail
         * @description The `detail` of the `409` from `POST /websites/{id}/runs` when that website already
         *     has a run in progress.
         *
         *     Carries the existing run's id and status, the same shape `WebsiteAlreadyExistsDetail`
         *     (`app.features.websites.schemas`) carries the existing website's id: a 409 that hands
         *     back nothing actionable makes the client build a second request just to find out what it
         *     collided with.
         */
        RunAlreadyInFlightDetail: {
            /**
             * Code
             * @default run_already_in_flight
             * @constant
             */
            code: "run_already_in_flight";
            /** Message */
            message: string;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "processing" | "completed" | "failed";
        };
        /**
         * RunAlreadyInFlightResponse
         * @description The **whole** `409` body, envelope included — see `WebsiteAlreadyExistsResponse` for
         *     why the envelope is a separate model from its `detail` (FastAPI wraps `detail` in a JSON
         *     object, so documenting the inner model directly in `responses=` would describe a shape no
         *     actual response has).
         */
        RunAlreadyInFlightResponse: {
            detail: components["schemas"]["RunAlreadyInFlightDetail"];
        };
        /**
         * RunDetailResponse
         * @description The full body of `GET /runs/{id}` — every list-item field, plus the two that are too
         *     large or too rarely needed for a list view.
         *
         *     A subclass of `RunListItemResponse`, the same relationship `WebsiteListItemResponse`
         *     has to `WebsiteResponse`: the detail view is the list item plus more, not an
         *     independently maintained sibling that could drift from it field by field.
         */
        RunDetailResponse: {
            /** Completed At */
            completed_at: string | null;
            /** Duration Ms */
            duration_ms: number | null;
            /** Error */
            error: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Llms Txt */
            llms_txt: string | null;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Stats */
            stats: {
                [key: string]: unknown;
            } | null;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "processing" | "completed" | "failed";
            /** Storage Path */
            storage_path: string | null;
            /**
             * Trigger
             * @enum {string}
             */
            trigger: "manual" | "scheduled";
            /**
             * Website Id
             * Format: uuid
             */
            website_id: string;
        };
        /**
         * RunLimitExceededDetail
         * @description The `detail` of the `429` from `POST /websites/{id}/runs` — either abuse cap.
         *
         *     `scope` is the discriminator a client branches on; `message` is prose for a human and is
         *     free to be reworded without breaking a client that reads `scope` and `limit` instead.
         */
        RunLimitExceededDetail: {
            /**
             * Code
             * @default run_limit_exceeded
             * @constant
             */
            code: "run_limit_exceeded";
            /** Limit */
            limit: number;
            /** Message */
            message: string;
            /** Resets At */
            resets_at: string | null;
            /**
             * Scope
             * @enum {string}
             */
            scope: "concurrent" | "daily";
        };
        /**
         * RunLimitExceededResponse
         * @description The **whole** `429` body, envelope included — same reasoning as
         *     `RunAlreadyInFlightResponse` above.
         */
        RunLimitExceededResponse: {
            detail: components["schemas"]["RunLimitExceededDetail"];
        };
        /**
         * RunListItemResponse
         * @description One row of `GET /websites/{id}/runs`.
         *
         *     Deliberately excludes `llms_txt` and `storage_path` — an artifact can be large and no
         *     list view renders it; `RunDetailResponse` below is the endpoint that returns them.
         */
        RunListItemResponse: {
            /** Completed At */
            completed_at: string | null;
            /** Duration Ms */
            duration_ms: number | null;
            /** Error */
            error: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Stats */
            stats: {
                [key: string]: unknown;
            } | null;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "processing" | "completed" | "failed";
            /**
             * Trigger
             * @enum {string}
             */
            trigger: "manual" | "scheduled";
            /**
             * Website Id
             * Format: uuid
             */
            website_id: string;
        };
        /**
         * RunStatsPoint
         * @description One bucket of `GET /websites/{id}/stats`'s `series`.
         *
         *     Every bucket in the requested window appears exactly once, in order — including buckets
         *     with zero runs, which report zeroes rather than being omitted (`RunsReader.
         *     website_stats`'s `_WEBSITE_STATS` zero-fills them with `generate_series`). `avg_pages`
         *     and `avg_duration_ms` are therefore never `null`: see `service.py`'s `_to_stats` for the
         *     rounding that turns SQL's already-zero-filled averages into these two fields.
         */
        RunStatsPoint: {
            /** Avg Duration Ms */
            avg_duration_ms: number;
            /** Avg Pages */
            avg_pages: number;
            /** Completed */
            completed: number;
            /** Failed */
            failed: number;
            /** Runs */
            runs: number;
            /**
             * T
             * Format: date-time
             */
            t: string;
        };
        /**
         * RunStatsTotals
         * @description The whole-window summary alongside `series` in `GET /websites/{id}/stats`.
         *
         *     Field names are `completed`/`failed`, matching `RunStatsPoint` above — not
         *     `total_completed`/`total_failed` — because they are still counts of completed/failed
         *     runs, merely summed over the whole window instead of one bucket.
         */
        RunStatsTotals: {
            /** Avg Duration Ms */
            avg_duration_ms: number;
            /** Avg Pages */
            avg_pages: number;
            /** Completed */
            completed: number;
            /** Failed */
            failed: number;
            /** Last Run At */
            last_run_at: string | null;
            /** Success Rate */
            success_rate: number | null;
            /** Total Runs */
            total_runs: number;
        };
        /**
         * ScheduleResponse
         * @description One website's schedule, as both schedules endpoints return it.
         *
         *     **`auto_publish` MUST NOT appear here, in either direction.** The column is reserved and
         *     unused in this milestone (its comment in `db/schema.prisma` says so directly): no code
         *     reads or writes it yet, and it exists only so that turning on publish-on-success later is
         *     a behaviour change rather than a migration on a table the cron tick is actively scanning.
         *     Exposing it now — even read-only — would let a client start depending on a value nothing
         *     in this system ever sets to anything but its default, and would give this API two things
         *     to keep in sync the day `auto_publish` does become real.
         *
         *     `interval_minutes` here is a plain `int`, **not** `ScheduleIntervalMinutes`. The allowlist
         *     on the request is an input guardrail — "these are the presets this product offers right
         *     now" — and the ticket that defined it notes arbitrary intervals may be allowed later
         *     without a migration. A response model that re-validated the same allowlist on the way out
         *     would turn any row outside it (a legacy value, a hand-seeded row, a future relaxation that
         *     ships before this model is updated) into a `500` on a plain `GET` — the read path failing
         *     for a reason that has nothing to do with reading.
         *
         *     `last_run_at` **is** exposed, read-only. It is not one of the two knobs
         *     `UpsertScheduleRequest` accepts, and this API never writes it — only the cron tick and the
         *     run pipeline (neither built yet) ever will. Surfacing it here is what lets a settings page
         *     show "last ran 3 hours ago" without a second endpoint.
         */
        ScheduleResponse: {
            /** Active */
            active: boolean;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Interval Minutes */
            interval_minutes: number;
            /** Last Run At */
            last_run_at: string | null;
            /** Next Run At */
            next_run_at: string | null;
            /**
             * Website Id
             * Format: uuid
             */
            website_id: string;
        };
        /**
         * ScheduleSummary
         * @description The compact view of a website's schedule, folded into the list response.
         *
         *     Like `LatestRunSummary`, a fragment: enough to render "every 6 hours, next at 14:00" and
         *     nothing else. The schedules feature owns the full representation and the endpoints that
         *     change it.
         */
        ScheduleSummary: {
            /** Active */
            active: boolean;
            /** Interval Minutes */
            interval_minutes: number;
            /** Next Run At */
            next_run_at: string | null;
        };
        /**
         * TriggerRunResponse
         * @description The body of `POST /websites/{id}/runs` on success.
         *
         *     Deliberately not `RunListItemResponse` or a slice of it: a just-triggered run has no
         *     `completed_at`, `duration_ms`, `stats`, or `error` worth returning, and reusing that
         *     model would mean either faking those fields or making them optional on a response that
         *     is supposed to be the simplest one this feature has.
         *
         *     Status `202 Accepted`, not `201 Created` (see the router): the row this describes has
         *     been written, but the crawl it names has only been queued, not completed — `201` would
         *     claim more than is true the instant this response leaves the server.
         */
        TriggerRunResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "processing" | "completed" | "failed";
        };
        /**
         * UpsertScheduleRequest
         * @description Body of `PUT /websites/{id}/schedule`.
         *
         *     Both fields are required — there is no partial update here. A schedule has exactly two
         *     knobs a caller controls (`active`, `interval_minutes`); `next_run_at` and `last_run_at`
         *     are derived or owned elsewhere (see `ScheduleResponse`), so there is nothing left for a
         *     `PATCH`-style optional field to mean.
         *
         *     Deliberately **not** `model_config = ConfigDict(extra="forbid")` — the rest of this
         *     codebase's request models do not set it either. An `auto_publish` key in the body is
         *     silently ignored rather than rejected; `tests/test_schedules_api.py` proves that ignoring
         *     it does not mean writing it — the column this API never touches stays whatever it already
         *     was.
         */
        UpsertScheduleRequest: {
            /**
             * Active
             * @description Whether this schedule should run automatically.
             */
            active: boolean;
            /**
             * Interval Minutes
             * @description Minutes between runs. One of the four supported presets: 60 (hourly), 360 (6-hourly), 1440 (daily), or 10080 (weekly).
             * @enum {integer}
             */
            interval_minutes: 60 | 360 | 1440 | 10080;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * WebsiteAlreadyExistsDetail
         * @description The `detail` of the `409` from `POST /websites`, carrying the id of the existing row.
         *
         *     The id is the point. Pasting a URL you already added is a normal thing to do from the
         *     landing page, and the useful response is "you already have this, here it is" — the
         *     frontend navigates to `website_id` instead of rendering an error the user cannot act on.
         *     A bare `409` would turn a one-click flow into a dead end.
         *
         *     A model rather than an ad-hoc dict so the shape appears in the OpenAPI document (see the
         *     router's `responses=`) and the frontend can generate a type for it.
         */
        WebsiteAlreadyExistsDetail: {
            /**
             * Code
             * @default website_already_exists
             * @constant
             */
            code: "website_already_exists";
            /** Message */
            message: string;
            /** Origin */
            origin: string;
            /**
             * Website Id
             * Format: uuid
             */
            website_id: string;
        };
        /**
         * WebsiteAlreadyExistsResponse
         * @description The **whole** `409` body, envelope included.
         *
         *     FastAPI serializes an `HTTPException`'s `detail` as `{"detail": <detail>}`, so this
         *     wrapper — not `WebsiteAlreadyExistsDetail` on its own — is what a client actually
         *     receives. Documenting the inner model directly in the route's `responses=` would put a
         *     schema in the OpenAPI document that no response ever matches, and any client generated
         *     from it would look for `website_id` one level too high.
         */
        WebsiteAlreadyExistsResponse: {
            detail: components["schemas"]["WebsiteAlreadyExistsDetail"];
        };
        /**
         * WebsiteListItemResponse
         * @description One row of `GET /websites`.
         *
         *     `latest_run` and `schedule` are **always `null` unless `?include=latest_run` was
         *     requested**. With it, each is `null` only when the website genuinely has no run / no
         *     schedule. The two cases are deliberately not distinguished in the payload: a caller that
         *     did not ask for the fold has no reason to tell "not requested" from "none exists", and a
         *     caller that did ask knows it asked.
         */
        WebsiteListItemResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            latest_run?: components["schemas"]["LatestRunSummary"] | null;
            /** Origin */
            origin: string;
            schedule?: components["schemas"]["ScheduleSummary"] | null;
            /** Title */
            title: string | null;
            /** Url */
            url: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
        };
        /**
         * WebsiteResponse
         * @description One website, as every endpoint in this feature returns it.
         *
         *     Carries `user_id` because the UI renders the owner and gates the delete control on it —
         *     and because `require_owner` (`app.core.auth.ownership`) takes the resource, not a bare
         *     id, so this field is what makes an instance of this model checkable. Exposing it to
         *     every signed-in caller is intended: this application is not multi-tenant, and who added
         *     a site is public information within it (ARCHITECTURE.md §4).
         */
        WebsiteResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Origin */
            origin: string;
            /** Title */
            title: string | null;
            /** Url */
            url: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
        };
        /**
         * WebsiteStatsResponse
         * @description The full body of `GET /websites/{id}/stats`.
         *
         *     `window` and `bucket` echo the request back (`bucket` is derived from `window`, never
         *     supplied by the caller — see `internals/stats_window.resolve_window`), so a client that
         *     only stores the response still knows what it is looking at.
         */
        WebsiteStatsResponse: {
            /**
             * Bucket
             * @enum {string}
             */
            bucket: "hour" | "day";
            /** Series */
            series: components["schemas"]["RunStatsPoint"][];
            totals: components["schemas"]["RunStatsTotals"];
            /**
             * Window
             * @enum {string}
             */
            window: "7d" | "30d" | "90d";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    get_run_runs__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_websites_websites_get: {
        parameters: {
            query?: {
                /** @description Set to `latest_run` to fold each website's most recent run and its schedule summary into the response. Omitted, both fields are null. */
                include?: "latest_run" | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebsiteListItemResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_website_websites_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWebsiteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebsiteResponse"];
                };
            };
            /** @description You have already added a website with this origin. The response carries the existing website's id so the client can navigate to it. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebsiteAlreadyExistsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_website_websites__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebsiteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_website_websites__id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_websites__id__runs_get: {
        parameters: {
            query?: {
                /** @description Return only runs with this status. An unrecognized value is a 422. */
                status?: ("pending" | "processing" | "completed" | "failed") | null;
                /** @description Page size. Values above the maximum (100) are silently clamped to it rather than rejected; `<= 0` is a 422. */
                limit?: number;
                /** @description Opaque pagination cursor from a previous page's `next_cursor`. Omit it to fetch the first page. Treat it as a blob — see `Page.next_cursor`. */
                cursor?: string | null;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_RunListItemResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_run_websites__id__runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TriggerRunResponse"];
                };
            };
            /** @description This website already has a pending or processing run — of any trigger, manual or scheduled. The response carries that run's id and status. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunAlreadyInFlightResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description The caller is over their concurrent- or daily-run cap. `detail.scope` says which; `detail.resets_at` is set only for the daily cap. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunLimitExceededResponse"];
                };
            };
        };
    };
    get_schedule_websites__id__schedule_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleResponse"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upsert_schedule_websites__id__schedule_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertScheduleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_website_stats_websites__id__stats_get: {
        parameters: {
            query?: {
                /** @description Time span to aggregate over. One of 7d, 30d, 90d; anything else is a 422. */
                window?: "7d" | "30d" | "90d";
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebsiteStatsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
