/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness-and-readiness probe, polled by Fly every 10 seconds.
         *
         *     **The HTTP status is always 200 as long as this process is alive — database health is
         *     reported in the body, never the status code.** This is deliberate: restarting a
         *     healthy web machine does nothing to fix a Postgres outage, it just adds a flapping
         *     fleet of machines on top of one. A non-200 here would make Fly do exactly that.
         *
         *     The database check (`SELECT 1`, budget `_DB_CHECK_TIMEOUT_SECONDS`) always runs, so
         *     `db` is always present: `"ok"` when it succeeds, `"timeout"` if it exceeds its budget,
         *     `"error"` for anything else. `status` is `"ok"` only when `db` is `"ok"`; otherwise
         *     it's `"degraded"`, so a caller that only reads `status` still gets an accurate signal
         *     without having to know `db`'s possible values.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/websites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Websites
         * @description List **every** website, from every user, most recently active first.
         *
         *     Not filtered by the caller, on purpose: this application is not multi-tenant and
         *     browsing everyone's sites is the product (ARCHITECTURE.md §4.1). `user_id` is present to
         *     require authentication and is intentionally not passed to the service.
         */
        get: operations["list_websites_websites_get"];
        put?: never;
        /**
         * Create Website
         * @description Register a website, owned by the caller.
         *
         *     The URL is validated by `CreateWebsiteRequest` before this runs, so a malformed one is a
         *     `422` that never reaches the service.
         */
        post: operations["create_website_websites_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/websites/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Website
         * @description Return one website. Any signed-in user may read any website; `404` if unknown.
         *
         *     The path parameter is `id`, not `website_id`, because the noun is already in the path
         *     (ARCHITECTURE.md §10.3). It shadows the `id` builtin inside this function body, which is
         *     the accepted cost of the route contract — nothing here calls `id()`.
         */
        get: operations["get_website_websites__id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Website
         * @description Delete a website the caller owns, along with its schedule and runs.
         *
         *     `403`, not `404`, when the caller is not the owner: `GET /websites/{id}` already returns
         *     this row to every signed-in user, so hiding its existence here would be inconsistent
         *     with the endpoint next to it (ARCHITECTURE.md §4, `app.core.auth.ownership`).
         *
         *     Returns `204` with no body — hence no `response_model` and a `None` return.
         */
        delete: operations["delete_website_websites__id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * CreateWebsiteRequest
         * @description Body of `POST /websites`.
         */
        CreateWebsiteRequest: {
            /**
             * Url
             * @description An absolute http:// or https:// URL. Stored as submitted; its normalized origin (lowercased scheme and host, default port and path removed) is what deduplicates it against your existing websites.
             * @example https://example.com/docs
             */
            url: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Response body for `GET /health`.
         *
         *     This DTO lives beside its route rather than in `app/features/` because health is an
         *     operational endpoint, not a product feature with a service, a reader, and a writer.
         *     It does touch Postgres — a bounded `SELECT 1`, see `_check_db` — but that is a
         *     liveness probe rather than data access, which is why it has no repository behind it.
         *
         *     `db` is required, never absent, because the check that produces it always runs —
         *     there is no code path that returns this response without having attempted it.
         */
        HealthResponse: {
            /**
             * Db
             * @enum {string}
             */
            db: "ok" | "error" | "timeout";
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
        };
        /**
         * LatestRunSummary
         * @description The compact view of a website's most recent run, folded into the list response.
         *
         *     A fragment of `WebsiteListItemResponse`, never an endpoint's response on its own — the
         *     runs feature owns the full run representation. Only the fields the websites table in the
         *     UI actually renders are here; anything more would make this a second, competing run DTO.
         */
        LatestRunSummary: {
            /** Completed At */
            completed_at: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Pages Crawled */
            pages_crawled: number | null;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "processing" | "completed" | "failed";
        };
        /**
         * ScheduleSummary
         * @description The compact view of a website's schedule, folded into the list response.
         *
         *     Like `LatestRunSummary`, a fragment: enough to render "every 6 hours, next at 14:00" and
         *     nothing else. The schedules feature owns the full representation and the endpoints that
         *     change it.
         */
        ScheduleSummary: {
            /** Active */
            active: boolean;
            /** Interval Minutes */
            interval_minutes: number;
            /** Next Run At */
            next_run_at: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * WebsiteAlreadyExistsDetail
         * @description The `detail` of the `409` from `POST /websites`, carrying the id of the existing row.
         *
         *     The id is the point. Pasting a URL you already added is a normal thing to do from the
         *     landing page, and the useful response is "you already have this, here it is" — the
         *     frontend navigates to `website_id` instead of rendering an error the user cannot act on.
         *     A bare `409` would turn a one-click flow into a dead end.
         *
         *     A model rather than an ad-hoc dict so the shape appears in the OpenAPI document (see the
         *     router's `responses=`) and the frontend can generate a type for it.
         */
        WebsiteAlreadyExistsDetail: {
            /**
             * Code
             * @default website_already_exists
             * @constant
             */
            code: "website_already_exists";
            /** Message */
            message: string;
            /** Origin */
            origin: string;
            /**
             * Website Id
             * Format: uuid
             */
            website_id: string;
        };
        /**
         * WebsiteAlreadyExistsResponse
         * @description The **whole** `409` body, envelope included.
         *
         *     FastAPI serializes an `HTTPException`'s `detail` as `{"detail": <detail>}`, so this
         *     wrapper — not `WebsiteAlreadyExistsDetail` on its own — is what a client actually
         *     receives. Documenting the inner model directly in the route's `responses=` would put a
         *     schema in the OpenAPI document that no response ever matches, and any client generated
         *     from it would look for `website_id` one level too high.
         */
        WebsiteAlreadyExistsResponse: {
            detail: components["schemas"]["WebsiteAlreadyExistsDetail"];
        };
        /**
         * WebsiteListItemResponse
         * @description One row of `GET /websites`.
         *
         *     `latest_run` and `schedule` are **always `null` unless `?include=latest_run` was
         *     requested**. With it, each is `null` only when the website genuinely has no run / no
         *     schedule. The two cases are deliberately not distinguished in the payload: a caller that
         *     did not ask for the fold has no reason to tell "not requested" from "none exists", and a
         *     caller that did ask knows it asked.
         */
        WebsiteListItemResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            latest_run?: components["schemas"]["LatestRunSummary"] | null;
            /** Origin */
            origin: string;
            schedule?: components["schemas"]["ScheduleSummary"] | null;
            /** Title */
            title: string | null;
            /** Url */
            url: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
        };
        /**
         * WebsiteResponse
         * @description One website, as every endpoint in this feature returns it.
         *
         *     Carries `user_id` because the UI renders the owner and gates the delete control on it —
         *     and because `require_owner` (`app.core.auth.ownership`) takes the resource, not a bare
         *     id, so this field is what makes an instance of this model checkable. Exposing it to
         *     every signed-in caller is intended: this application is not multi-tenant, and who added
         *     a site is public information within it (ARCHITECTURE.md §4).
         */
        WebsiteResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Origin */
            origin: string;
            /** Title */
            title: string | null;
            /** Url */
            url: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_websites_websites_get: {
        parameters: {
            query?: {
                /** @description Set to `latest_run` to fold each website's most recent run and its schedule summary into the response. Omitted, both fields are null. */
                include?: "latest_run" | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebsiteListItemResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_website_websites_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWebsiteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebsiteResponse"];
                };
            };
            /** @description You have already added a website with this origin. The response carries the existing website's id so the client can navigate to it. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebsiteAlreadyExistsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_website_websites__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebsiteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_website_websites__id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
